version: '3.8'
services:
    microservice_01:
        build:
            args:
                user: microservice_01
                uid: 1001
            context: ./
            dockerfile: DockerFile
        image: micro_01
        restart: always
        working_dir: /var/www
        depends_on:
            - redis
        volumes:
            - ./:/var/www
        networks:
            - micro_01

    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        ports:
            - 8001:80
        networks:
            - micro_01

    mysql:
        image: mysql:5.7.22
        restart: always
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3308:3306
        networks:
            - micro_01

    queue:
        build:
            args:
                user: microservice_01
                uid: 1001
            context: ./
            dockerfile: DockerFile
        restart: always
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        networks:
            - micro_01

    redis:
        image: redis:latest
        networks:
            - micro_01

networks:
    micro_01:
        driver: bridge
